### ISSUE TITLE
Deprecate HTTP!

### ISSUE THREAD

**Issue by pde** [TCNCoalition/website#11]
Privacy and security groups shouldn't have websites that serve HTTP ;)

Looks like the site is behind Cloudlfare, so [these instructions](https://support.cloudflare.com/hc/en-us/articles/204183088-Understanding-HSTS-HTTP-Strict-Transport-Security-) and maybe at a lower priority [these too](https://support.cloudflare.com/hc/en-us/articles/360024787372-End-to-end-HTTPS-with-Cloudflare-Part-1-conceptual-overview) are worth following.

**Comment by harperreed** [comment]
I am pretty sure i have enabled this. please test and let me know. 

Closing until i hear otherwise
